name: Deployment pipeline with NX
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    steps:
      - name: Bring me the last commit
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install node
        uses: actions/setup-node@v4
        # Cache node_modules
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: install dependencies
        run: npm ci --no-audit --no-fund

      - uses: nrwl/nx-set-shas@v3

      - run: npx nx affected --target=api-v2 --base=main --head=HEAD --plain --parallel

      # Deploy API-v2 to Vercel
      - name: Deploy to Vercel
        run: |
          curl -X POST -H 'Content-Type: application/json' -d '{"ref":"main"}' https://api.vercel.com/v1/integrations/deploy/prj_SEe0H4I43JzsttMSNF12veaSZkin/fNu7EJDPuX
